#!/Users/kilian/.nvm/v0.11.13/bin/node

var readline = require('readline')

var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
})

rl.on('line', function (cmd) {
  console.log('line: %s', cmd)
})