#!/usr/bin/env node

var readline = require('readline')
  , deploy = require('../scripts/deploy').deploy

readline.createInterface({
  input: process.stdin,
  output: {}
}).on('line', function (refs) {
  refs = refs.split(' ')

  var sourceRef = refs[0]
  var sourceHash = refs[1]
  var destRef = refs[2]
  var destHash = refs[3]

  deploy(destRef)
})